### PR TITLE
🥔✨ `Neighborhood`: Error pages use the Convene layout

### PR DESCRIPTION
**Pull request by anaulin**
- https://github.com/zinc-collective/convene/issues/1658

Fixes https://github.com/zinc-collective/convene/issues/1658 by adding basic error pages to replacethe standard Rails error pages. These new pages will show the standard Convene UI chrome, and will include things like the Space name in the breadcrumbs, if one is available.

It's pretty barebones for now, but at least it gives a way back to the app.

It also proved surprisingly hard to test this controller in a request or Capybara-based test, so instead I wrapped the less straightforward part of this code in a `rescue` block.

#### 404 error
image

#### Some other error
image

#### 404 error
image

#### Some other error
image

For my and others' reference, to test this locally you need to set `config.consider_all_requests_local = false` in your `development.rb`.

### CODE REVIEW

**Comment by anaulin** [comment]
There is some wonky interaction happening between my custom error pages and that one spec, sigh.

**Review by zspencer — APPROVED** [review]
This is great! Thank you!

**Comment by anaulin** [comment]
Thank you for helping push this over the finish line, @zspencer !

**Comment by zspencer** [comment]
cats-teamwork

**Pull request merged**
