### PR TITLE
Furniture: remove default Turbo Frame

### PR DESCRIPTION
**Pull request by zspencer**
This was added to try and make it easier to make dynamic websites, however turbo-frames are really not the best use-case for this and we are leaning more fully into turbo-streams and regular html.

I am hopeful this will also fix the weird display bug with the Marketplace on piikup-marketplace.convene.zinc.coop as well.

- [x] Smoke test! There's lots of stuff that is weird
- [x] Get the Feature tests working

### CODE REVIEW

**Review by anaulin — COMMENTED** [review]
Changes LGTM but this PR is now in draft mode, so I'm unclear if this is ready for review or...?

**Comment by zspencer** [comment]
I was doing some smoke testing and things were not very happy; so I decided to pull it back into draft.

**Review by anaulin — APPROVED** [review]

**Comment by anaulin** [comment]
This is now green and ready for a final review, @zspencer (I "approved" it since it is technically your PR -- please have a look and merge it if it looks fine to you)

**Comment by zspencer** [comment]
Thanks @anaulin ! I did some smoke testing and a bit more tidying of the shift in the UX and will merge when CI goes green!

**Pull request merged**
