### PR TITLE
Add FUNDING.yml to display sponsorship link on repo

### PR DESCRIPTION
**Pull request by anaulin**
Instructions on format for this file can be found here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

### CODE REVIEW

**Review by zspencer — APPROVED** [review]
🚢 :it:

**Comment by anaulin** [comment]
According to the docs, there is a "Features" section under "Settings" where the sponsorship button for the repo can be enabled, but I don't see that section at all. Maybe only repo owners can do that, @zspencer can you take a look? (The instructions are at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository)

**Comment by anaulin** [comment]
Enabled the sponsorship button on the Convene repo. For reference, it can be turned on or off under Settings -> General
Screenshot 2023-03-06 at 12 52 56 PM

**Comment by zspencer** [comment]
Rockin'!

**Pull request merged**
