### PR TITLE
✨ Space config displays help text

### PR DESCRIPTION
**Pull request by KellyAH**
- For https://github.com/zinc-collective/convene/issues/1585

# Changes
- Add help text to the Space config page when a Space is missing sections, an entrance and memberships.

Screenshot 2023-06-21 at 6 44 21 PM

### CODE REVIEW

**Comment by KellyAH** [comment]
gah i forgot to add co-authors for ya'll to the the commit message. I'll add it on the merge commit message.

**Comment by anaulin** [comment]
No worries about the co-author lines, it's not a big deal!

**Review by anaulin — APPROVED** [review]
This looks good, thank you!

**Review by zspencer — APPROVED** [review]
Dig it!

**Pull request merged**
