### PR TITLE
Massive Refactor of Steps, Pages, and Components

### PR DESCRIPTION
**Pull request by zspencer**
OK, the goal here is to:

- Shovel all the interactions with `selenium-webdriver` down into `Page` and `Component` classes; so that our step definitions never have to think about Selenium
- Get JSDoc plugged in for native type-hinting without requiring us to go all-in on TypeScript
- Move us away from having multiple items on `this`; or at least keeping the `this` items down to something like `this.session` and/or `this.factory`so that we have much less implicit connections between steps.
- Pull responsibility off of the `SpacePage` and into child `Component` objects or sibling `Page`s.

Hopefully this will also make it a bit easier to reason about what particular pieces of the test suite are doing; by giving us more affordances for dropping documentation  and type signatures.

### CODE REVIEW

**Comment by anaulin** [comment]
💚  🥦  🧹

**Comment by zspencer** [comment]
The two remaining failures appear to be because we're not creating a brand-new-space on each test-run... I want to muse a bit on that; because I'd _love_ for us to spawn new spaces with the blueprint(s) that we expect for the particular test case we're running; but to do so I'd need to expose an API for creating Spaces... which may be fine but I think I'm out of spoons on it for not...

**Review by anaulin — APPROVED** [review]
This looks like a great refactor that will enable us to write tests more sustainably. Thank you!

**Review by anaulin — APPROVED** [review]
But really.

**Pull request merged**
