### PR TITLE
split ci pipeline so test job depends on build job

### PR DESCRIPTION
**Pull request by KellyAH**
## Problem:
CI pipeline currently runs as 1 job that executes everything sequentially (1. builds the app, 2. runs tests, 3. etc).

## Fix:
Break up the pipeline so after the app is built, unit, integration, and story tests run in parallel.

1. build app
2. --> run unit tests
    --> run int tests
    --> run browser tests

### CODE REVIEW

**Comment by KellyAH** [comment]
Closing. Gonna try to refactor [test-convene-web.yml](https://github.com/zinc-collective/convene/blob/main/.github/workflows/test-convene-web.yml)  to make it easier to understand what it's doing.

**Comment by zspencer** [comment]
Yea, I think decomposing into separate "jobs?" or whatever they're called is probably the next step after the clarifying bits.

Ideally we would have a `build` job and `test` job; and then we could decompose the `test` job into `test-features` and `test-rspec`

**Comment by KellyAH** [comment]
TODO: @KellyAH 
## parallel CI test runs

- [ ] Cleanup yml
  - [ ]  add names - https://github.com/zinc-collective/convene/pull/1054
  - [ ]  do we need [brew](https://github.com/zinc-collective/convene/pull/1054#discussion_r1081553023)
  - [ ] do we need [inotify watchers](https://github.com/zinc-collective/convene/pull/1054#discussion_r1081553464)?
- [ ]  Break out seperate sequential jobs
  - [ ]  `test-rspec` - (enviro + run unit tests)
  - [ ] `build` -  (can start rails app)
  - [ ] `test-features` - (browser enviro + run browser tests)
- [ ] Make test jobs run in parallel if `build` job is successful

**Comment by KellyAH** [comment]
work is continued in https://github.com/zinc-collective/convene/pull/1060

**Pull request closed without merging**
