### PR TITLE
Remove lingering obsolete references to video spaces

### PR DESCRIPTION
**Pull request by anaulin**
Random debris left over form our removal of Jitsi video

### CODE REVIEW

**Review by zspencer — APPROVED** [review]
Love it!

**Comment by rosschapman** [comment]
Minor, but should the reference to Jitsi disappear from the Philosophy section of https://convene.zinc.coop/? 

image

**Comment by zspencer** [comment]
Probably! If you'd like we can invite you to be a `Member` on the `convene.zinc.coop` space; which would allow you to update the copy.

**Comment by rosschapman** [comment]
@zspencer Sure, I'd be happy to help do that.

**Comment by anaulin** [comment]
Good catch on the Jitsi thing. All the copy on that landing page needs a rethink -- maybe even breaking it up a bit into first something more punchy and marketing-y ("here is why you want a Convene Space") with links / teasers to sections about our philosophy, etc?

**Comment by zspencer** [comment]
I've invited you to convene.zinc.coop, @rosschapman 

Re: More Punchy - Yes ! agree!!!

**Pull request merged**
