### PR TITLE
🌸 `Themes`/ `Mobile`:  Eliminate top navigation

### PR DESCRIPTION
**Pull request by zspencer**
- https://github.com/zinc-collective/convene/issues/832
- https://github.com/zinc-collective/convene/issues/621
- https://github.com/zinc-collective/convene/issues/833

The top navigation is a bit excessive, especially on mobile. 

This brings the UI to a much cleaner place; with breadcrumbs and sign in / out only on the bottom of the page.

## After
Screenshot 2023-10-04 at 17-34-42 Convene - The Oakland Community Food Network

## Before
Screenshot 2023-09-30 at 16-18-18 Convene - Zee's Space

### CODE REVIEW

**Comment by anaulin** [comment]
I agree that the current setup with Breadcrumbs and "Your account" and "Sign out" is a bit much ("Sign out" should be an option in the "Your Account" menu, and it should show your email address or name, instead of "Your Account"), but I think we need to replace it with some minimal framing or title for what the user is seeing. Otherwise it is not clear what am I looking at, it doesn't say "Marketplace" anywhere clearly, and it doesn't say "Piikup", I'm just dropped into "choose your delivery address", without confirmation of which site I'm on.

Showing the "room" name in the header was serving a bit of this purpose, because that way you can land on a page and see e.g. "Crumble & Whisk" at the top, but maybe we should instead have a header on the Gizmo itself, so it would say "Crumble & Whisk Marketplace" at the top (and maybe the content can be configurable).

**Comment by zspencer** [comment]
>  It is not clear what am I looking at, it doesn't say "Marketplace" anywhere clearly, and it doesn't say "Piikup", I'm just dropped into "choose your delivery address", without confirmation of which site I'm on.
>
> Showing the "room" name in the header was serving a bit of this purpose, because that way you can land on a page and see e.g. "Crumble & Whisk" at the top, but maybe we should instead have a header on the Gizmo itself, so it would say "Crumble & Whisk Marketplace" at the top (and maybe the content can be configurable).

I like the idea of having the Marketplace include the name of both the Space and the Room (i.e. `Crumble & Whisk on the Piikup Marketplace`) and we could make that configurable!

**Comment by zspencer** [comment]
@anaulin how do you like it now? I put in a header on the Marketplace; which I think it wanted anyway; and that should better ground people so they know where they're at.

**Review by anaulin — APPROVED** [review]
I like it!

**Pull request merged**
